### ISSUE TITLE
Update 'reset' method to reset new fields

### ISSUE THREAD

**Issue by aOverholt** [aOverholt/fe-dev-tools-shadows#6]
As a user, I expect the 'reset' button to reset all fields back to their default values.

Acceptance Criteria
- [ ] The 'reset' button resets every field back to the default values

**Comment by k0msenapati** [comment]
What exactly do you want to do here? 
Reset all the inputs or something else?

**Comment by aOverholt** [comment]
Hi @kom-senapati, yes! 
I added a few more fields after setting up the 'reset' button, but I forgot to update the function to reset those fields as well.

**Comment by k0msenapati** [comment]
Would you like to assign me this issue ?
